default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: kelly
  template: template0
development:
  <<: *default
  database: lunchy_dev

test:
  <<: *default
  database: lunchy_test
